services:
  app:
    build: .
    container_name: database-memory
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - database-memory-ntw

networks:
  database-memory-ntw:
    driver: bridge
