POST http://localhost:3333/videos
Content-Type: application/json

{
    "titulo": "video aula 01",
    "descricao": "Esse é o video 01",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/1cea80e7-4a28-4fa2-bdab-97a5eb31c90a
Content-Type: application/json

{
    "titulo": "video 02s",
    "descricao": "Esse é o video 01",
    "duration": 180
}

###

DELETE  http://localhost:3333/videos/1cea80e7-4a28-4fa2-bdab-97a5eb31c90a
Content-Type: application/json